use_default_settings: true

general:
  debug: false
  instance_name: "My SearXNG"

search:
  safe_search: 0
  autocomplete: ""
  default_lang: "zh-CN"
  formats:
    - html
    - json

server:
  bind_address: "0.0.0.0"
  port: 8080
  secret_key: "zzzzgg"
  limiter: false
  image_proxy: false

engines:
  - name: google
    engine: google
    shortcut: go

  - name: bing
    engine: bing
    shortcut: bi

  - name: brave
    engine: brave
    shortcut: br

  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg

  - name: wikipedia
    engine: wikipedia
    shortcut: wp

  - name: github
    engine: github
    shortcut: gh
